# Generated by Django 4.1.3 on 2022-11-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correoElectronico', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('consulta', models.CharField(max_length=500)),
            ],
        ),
    ]
