# Generated by Django 4.1.3 on 2022-11-21 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_mensajecontacto_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='celular',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='dni',
            field=models.BigIntegerField(),
        ),
    ]
