# Generated by Django 4.1.3 on 2022-11-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_mensajecontacto_fecha_alter_mensajecontacto_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.BigIntegerField()),
                ('precio', models.BigIntegerField()),
            ],
        ),
    ]
