# Generated by Django 4.1.3 on 2022-11-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='peso',
            field=models.CharField(default=8, max_length=255),
            preserve_default=False,
        ),
    ]
