# Generated by Django 4.1.3 on 2022-11-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_carritodecompras'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritodecompras',
            name='cantidadProducto',
            field=models.BigIntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carritodecompras',
            name='total',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.FloatField(),
        ),
    ]
