# Generated by Django 4.1.3 on 2022-11-28 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venta', '0007_carritodecompras_cantidadproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='informacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('apartamento', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('metodo', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
