# Generated by Django 4.1.3 on 2022-11-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_informacionpago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionpago',
            name='celular',
            field=models.BigIntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='informacionpago',
            name='dni',
            field=models.BigIntegerField(max_length=255),
        ),
    ]
