# Generated by Django 4.1.3 on 2022-11-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0010_alter_informacionpago_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionpago',
            name='celular',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='informacionpago',
            name='dni',
            field=models.CharField(max_length=255),
        ),
    ]
