# Generated by Django 4.1.3 on 2022-12-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_productos_id_stripe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='id_stripe',
            new_name='stripe_id',
        ),
    ]
