# Generated by Django 4.1.3 on 2022-12-02 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venta', '0013_rename_id_stripe_productos_stripe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoPago', models.CharField(max_length=255)),
                ('cantidadProducto', models.BigIntegerField()),
                ('total', models.FloatField()),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('apartamento', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('celular', models.BigIntegerField()),
                ('correo', models.CharField(max_length=255)),
                ('metodo', models.CharField(max_length=255)),
                ('dni', models.BigIntegerField()),
                ('estadoEntrega', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.productos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
